### PR TITLE
Aishwar's jounrey added

### PR DESCRIPTION
**Pull request by mrworld196wide**
## Checklist:

- [ +] My code follows the style guidelines of this project
- [ +] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ +] I have made corresponding changes to the documentation
- [ +] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by mrworld196wide** [comment]
added my journey

**Review by hritesh94 — COMMENTED** [review]
It looks good

**Review by vikasganiga05 — CHANGES_REQUESTED** [review]
Hi, you may forgot to add your new entry to [Data.json](https://github.com/collab-community/journey-book/blob/main/Data.json) file.

> Here is the format of a new entry :point_down: 

```json
{
  "name": "YOUR_NAME",
  "username": "YOUR_GITHUB_USERNAME",
  "avatar": "https://github.com/YOUR_GITHUB_USERNAME.png"
}
```

Please follow [How to contribute](https://github.com/collab-community/journey-book#how-to-contribute) or [contribution guidelines](https://github.com/collab-community/journey-book/blob/main/.github/CONTRIBUTING.md) for more info.

**Comment by mrworld196wide** [comment]
I added my current journey in tech and life.
Also updated Data.json

**Review by vikasganiga05 — APPROVED** [review]
Looks good to me :+1: Thanks for adding your journey. The GitHub, LinkedIn & StackOverflow icons will not look good in a dark theme.

**Comment by Adarsh-jaiss** [comment]
- @vikasganiga05  please resolve the merge confilcts and kindly merge the PR

**Pull request merged**
