### PR TITLE
Journey added

### PR DESCRIPTION
**Pull request by kelvinparmar**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [x] Test A
- [x] Test B

## Checklist:

- [✅] My code follows the style guidelines of this project
- [✅] I have performed a self-review of my own code
- [✅] I have commented my code, particularly in hard-to-understand areas
- [✅] I have made corresponding changes to the documentation
- [✅]  My changes generate no new warnings
- [✅] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by kelvinparmar** [comment]
Hey @Adarsh-jaiss what is the error in my pull request?

**Review by Adarsh-jaiss — CHANGES_REQUESTED** [review]
--  kindly fix the avatar thing, and replace it via your GitHub link + .png

**Comment by kelvinparmar** [comment]
How? @Adarsh-jaiss

**Comment by Adarsh-jaiss** [comment]
> How? @Adarsh-jaiss

IMG_20220813_112236


Like this

**Comment by kelvinparmar** [comment]
Ha but how can I do this ? I have no Idea? @Adarsh-jaiss

**Comment by Adarsh-jaiss** [comment]
"Avatar": "https://github.com/kelvinparmar.png"

**Review by Adarsh-jaiss — APPROVED** [review]

**Comment by Adarsh-jaiss** [comment]
Looks perfect :)

**Comment by KendallDoesCoding** [comment]
> > How? @Adarsh-jaiss
> 
> IMG_20220813_112236
> 
> Like this

kya hua here?

**Pull request merged**
