### PR TITLE
Data added

### PR DESCRIPTION
**Pull request by anjali112-bit**
I have included my information in journey book which includes my recent projects,motivation quotes ,my hobbies and links to connect with me.

### CODE REVIEW

**Comment by Adarsh-jaiss** [comment]
- please update the data.json file as well :)

**Review by Adarsh-jaiss — APPROVED** [review]

**Review by vikasganiga05 — CHANGES_REQUESTED** [review]
Hi, you may forgot to add your new entry to [Data.json](https://github.com/collab-community/journey-book/blob/main/Data.json) file.

> Here is the format of a new entry :point_down: 

```json
{
  "name": "YOUR_NAME",
  "username": "YOUR_GITHUB_USERNAME",
  "avatar": "https://github.com/YOUR_GITHUB_USERNAME.png"
}
```

Please follow [How to contribute](https://github.com/collab-community/journey-book#how-to-contribute) or [contribution guidelines](https://github.com/collab-community/journey-book/blob/main/.github/CONTRIBUTING.md) for more info.

**Comment by anjali112-bit** [comment]
Updated the json file.

**Comment by anjali112-bit** [comment]
Yeah added my file to json . Hoped u received the pr.

**Pull request merged**
