### PR TITLE
grammar/spelling in readme

### LINKED ISSUE #68: style: Grammar mistakes in README file
While reading the README file, i noticed som grammar mistakes, which if corrected, would enhance the readability of the README.md file.

It would also help others to better understand and read the procedures to joining our community. Screenshots below

Screenshot from 2022-07-26 14-24-24
- This should be "a small" or "a little"

Screenshot from 2022-07-26 14-25-45
Screenshot from 2022-07-26 14-24-54
- Punctuation marks are missing in this sections. And a few word choices, could be corrected.

### PR DESCRIPTION
**Pull request by 05e**
fixes #68 

this fixes the grammar and spelling in README.md as request in #68

### CODE REVIEW

**Review by Ebukachuqz — COMMENTED** [review]
It's okay.

**Review by Ebukachuqz — COMMENTED** [review]
Please could you edit steps in `How to contribute` as:
3. Share your tech journey and achivements
4. As you learn something new, you can update your README file, especially if you don't have any achivements currently.

**Comment by 05e** [comment]
done as requested

**Review by KendallDoesCoding — APPROVED** [review]

**Comment by KendallDoesCoding** [comment]
@Adarsh-jaiss @Ebukachuqz Please review and will merge, looks good to me.

**Review by Ebukachuqz — APPROVED** [review]
All good. Ready to be merged.

**Comment by KendallDoesCoding** [comment]
> All good. Ready to be merged.

Thanks.

**Comment by KendallDoesCoding** [comment]
@05e Thanks for your contribution, make sure you join this organization/community by creating a issue in our repo become-a-member. Thanks again :)!

**Comment by Adarsh-jaiss** [comment]
- looks good :)

**Pull request merged**
