### PR TITLE
Added Journey of Agrim-Sharma174

### PR DESCRIPTION
**Pull request by Agrim-Sharma174**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by KendallDoesCoding — CHANGES_REQUESTED** [review]
Fix grammer issues.

**Review by Agrim-Sharma174 — COMMENTED** [review]
Suggested changes made

**Comment by KendallDoesCoding** [comment]
Why did you assign it to me @Adarsh-jaiss. You should just assign me to
review lol

**Review by KendallDoesCoding — APPROVED** [review]

**Comment by KendallDoesCoding** [comment]
Perfect. Will merge when I'm on my laptop. Unable to merge from Github app for some reason.

**Comment by KendallDoesCoding** [comment]
Perfect. Will merge when I'm on my laptop. Unable to merge from Github app for some reason.

**Comment by KendallDoesCoding** [comment]
@Adarsh-jaiss Please change branch protection to remove base branch requires all commits to be verified. Can't merge this PR till then.

**Comment by KendallDoesCoding** [comment]
> @Adarsh-jaiss Please change branch protection to remove base branch requires all commits to be verified. Can't merge this PR till then.

@Adarsh-jaiss - this is awaiting you, please do at the earliest.

**Comment by KendallDoesCoding** [comment]
Thanks for your contribution @Agrim-Sharma174!

**Pull request merged**
