### PR TITLE
feat: update user cards on home page

### LINKED ISSUE #40: [FEAT]: Create a user card to show users in the home page
**Is your feature request related to a problem? Please describe.**
After implementing the docsify. Create a user card to display users on the home page which links to their respective journeys.

**Describe the solution you'd like**
I came up with the wireframe for the user-card :point_down: 

image

**Additional context**
Make sure to use a single color in the card UI design to make it simple and match the docsify theme.

### PR DESCRIPTION
**Pull request by vikasganiga05**
## Fixes Issue

Closes #40 

## Description

Thanks, @Prakharsharma2206 for your contribution. Updated the user cards on the home page. Under the Screenshots section I provided some examples please take a look at them :point_down: 

Here you can see the live preview of this PR &rarr; **[LIVE PREVIEW](https://raw.githack.com/vikasganiga05/journey-book/feat-40-user-card/index.html)**

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] Any dependent changes have been merged and published in downstream modules

## Screenshots

I made this PR using the Second Card Example.
Please share your thoughts on the below examples.

<table>
  <tr>
    <th>First Card Example (Light)</th>
     <th>First Card Example (Dark)</th>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
 </table>

<table>
  <tr>
    <th>Second Card Example (Light)</th>
     <th>Second Card Example (Dark)</th>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
 </table>

## Note to reviewers

I used colors provided by [docsify-darklight-theme](https://docsify-darklight-theme.boopathikumar.me/) to match the theme.

### CODE REVIEW

**Review by KendallDoesCoding — COMMENTED** [review]
Looks amazing, but can you put it little to the left, in my opinion there is too much spacing left.

image

**Comment by vikasganiga05** [comment]
> Looks amazing, but can you put it little to the left, in my opinion there is too much spacing left.
> 
> image

Removed the extra spacing from it. Please check now.

**Comment by KendallDoesCoding** [comment]
The space is still there, the cards are not aliging exactly under the gitpod button start

**Comment by vikasganiga05** [comment]
> The space is still there, the cards are not aliging exactly under the gitpod button start

Sorry, I don't understand which space your talking about. See the cards are perfectly aligned to the GitPod button :point_down: 

image

**Comment by KendallDoesCoding** [comment]
Hi, seems to be fixed now, there was a issue with the LIVE PREVIEW.

**Comment by KendallDoesCoding** [comment]
Thanks for your contribution @vikasganiga05

**Review by KendallDoesCoding — APPROVED** [review]

**Comment by vikasganiga05** [comment]
> Thanks for your contribution @vikasganiga05

It was my pleasure to work on this :slightly_smiling_face:

**Pull request merged**
