### PR TITLE
Hritesh94 patch 1

### PR DESCRIPTION
**Pull request by hritesh94**
## Description

Deleted  my name in 19 in sidebar.md 

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [x] Test A
- [x] Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by hritesh94 — COMMENTED** [review]
Looks ok to me

**Comment by vikasganiga05** [comment]
This is a duplicate of #142 PR

**Review by hritesh94 — COMMENTED** [review]
ok will delete it

**Comment by vikasganiga05** [comment]
> ok

Your PR is already merged :slightly_smiling_face:

**Comment by hritesh94** [comment]
Thank you very much , as i am new to all this open source contribution , I am trying to understand it , again thank you

**Comment by vikasganiga05** [comment]
> Thank you very much , as i am new to all this open source contribution , I am trying to understand it , again thank you

All the best for your open-source journey :+1:

**Pull request closed without merging**
