### PR TITLE
added journey- bugsy

### PR DESCRIPTION
**Pull request by bugsyy157**
added my journey in the journey book

### CODE REVIEW

**Review by vikasganiga05 — CHANGES_REQUESTED** [review]
Hi, you may forgot to add your new entry to [Data.json](https://github.com/collab-community/journey-book/blob/main/Data.json) file.

> Here is the format of a new entry :point_down: 

```json
{
  "name": "YOUR_NAME",
  "username": "YOUR_GITHUB_USERNAME",
  "avatar": "https://github.com/YOUR_GITHUB_USERNAME.png"
}
```

AND

Also, rename the markdown journey file `bugsy.md` to `bugsyy157.md`

Please follow [How to contribute](https://github.com/collab-community/journey-book#how-to-contribute) or [contribution guidelines](https://github.com/collab-community/journey-book/blob/main/.github/CONTRIBUTING.md) for more info.

**Comment by bugsyy157** [comment]
Sure...will do it👍

**Review by vikasganiga05 — APPROVED** [review]
It looks good to me. Thanks for your contribution :tada:
- Thank you so much Abhishek Yadav for sharing your journey till now.
- We are waiting for more contributions from you :green_heart:

**Comment by bugsyy157** [comment]
Learned few things from this...hope to learn more!!

**Pull request merged**
