### PR TITLE
Ahnafahamed

### PR DESCRIPTION
**Pull request by AhnafAhamed**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [x] checked whether my profile appears in the website

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by vikasganiga05 — COMMENTED** [review]
Hi @AhnafAhamed , Can you please write more about your journey? If you want to know what exactly your journey should include please refer to [What should I share in my journey?](https://collab-community.github.io/journey-book/#/_pages/what-should-i-share).

**Review by vikasganiga05 — CHANGES_REQUESTED** [review]
Hi @AhnafAhamed , Can you please write more about your journey? If you want to know what exactly your journey should include please refer to [What should I share in my journey?](https://collab-community.github.io/journey-book/#/_pages/what-should-i-share).

**Comment by AhnafAhamed** [comment]
@vikasganiga05 thank you for the feedback I have added the changes

**Review by vikasganiga05 — APPROVED** [review]
It looks good to me. Thanks for your contribution :tada:
- Thank you so much Ahnaf Ahamed for sharing your journey till now.
- We are waiting for more contributions from you :green_heart:

**Pull request merged**
