### PR TITLE
docs: update contributing guidelines

### PR DESCRIPTION
**Pull request by vikasganiga05**
## Description

I added clear instructions on contributing guidelines. This helps beginner contributors to add their journey to the projects easily. Also, I added a style guide for git commit messages. Our Git commit messages must be formatted. This format leads to easier-to-read commit history.

> If you have any improvements or fixes please let me know :slightly_smiling_face: 

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] Any dependent changes have been merged and published in downstream modules

## Screenshot

image

### CODE REVIEW

**Comment by Adarsh-jaiss** [comment]
-- everything seems to be perfect
-- what's your views @KendallDoesCoding

**Review by KendallDoesCoding — APPROVED** [review]
LGTM ✔️

**Comment by KendallDoesCoding** [comment]
Thanks @vikasganiga05

**Comment by vikasganiga05** [comment]
It's my pleasure :pray:

**Pull request merged**
