### PR TITLE
Added a summary of my journey and my contact links

### PR DESCRIPTION
**Pull request by Badbatunde**
## Description

I added a summary of my tech journey in the journeys folder and added my details in the Data.json file.

Fixes # (issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by vikasganiga05 — APPROVED** [review]
It looks good to me. Thank you Habeeb for adding your journey :pray: 

> **Note** This PR may get some conflicts after merging #131 PR. So, please wait for the PR to get merged first.

Thank You :pray:

**Review by vikasganiga05 — APPROVED** [review]
I resolved the merge conflict. Now it looks good to me. Thanks, Habeeb for adding your journey.

**Review by Adarsh-jaiss — APPROVED** [review]

**Comment by Badbatunde** [comment]
My journey (Habeeb B. Oyesile) is not displaying on the journey book.
When clicked, it displays: "404- Not found"

How can this be fixed? thanks.

Screenshot (91)

**Comment by vikasganiga05** [comment]
> My journey (Habeeb B. Oyesile) is not displaying on the journey book. When clicked, it displays: "404- Not found"
> 
> How can this be fixed? thanks.
> 
> Screenshot (91)

Sorry, it's my mistake I did not correctly check the PR before merging. Your journey file should rename from `Badbatunde.md` to `badbatunde.md`. I have renamed it in this commit &rarr; https://github.com/collab-community/journey-book/commit/5c9bb563a8263ad127fea4445c1fc7cb7a24dd93 And your journey page is now live. Thank you :pray:

**Comment by Badbatunde** [comment]
Oh, I did not notice the difference.
I sincerely apologise for that.

Thanks for fixing it btw, that was fast.

**Comment by vikasganiga05** [comment]
> 

Your welcome :slightly_smiling_face:

**Pull request merged**
